### ISSUE TITLE
Swift_Mime_Message  problem

### ISSUE THREAD

**Issue by janva255** [rdanusha/LaravelElasticEmail#3]
Declaration of Rdanusha\LaravelElasticEmail\ElasticTransport::send(Swift_Mime_Message $message, &$failedRecipients = NULL) must be compatible with Swift_Transport::send(Swift_Mime_SimpleMessage $message, &$failedRecipients = NULL)

**Comment by rdanusha** [comment]
Can you paste your code block here ?

**Comment by rdanusha** [comment]
can you paste your code block here ?

**Comment by janva255** [comment]
@rdanusha I was using another provider and it worked well, classic laravel mail usage, then used your package and it throws that, tell me what part do you need in specific and i'll show you.

**Comment by rdanusha** [comment]
Hi @janva255 , Just paste your send mail code. There are many Laravel Elastic mail providers but doesnt support to attachments.

**Comment by janva255** [comment]
```

Mail::to($user->email, $user->user)
->send(new ConfirmMail($token));

<?php

namespace App\Mail;

use Illuminate\Bus\Queueable;
use Illuminate\Mail\Mailable;
use Illuminate\Queue\SerializesModels;
use Illuminate\Contracts\Queue\ShouldQueue;

class ConfirmMail extends Mailable
{
    use Queueable, SerializesModels;

    /**
     * Create a new message instance.
     *
     * @return void
     */

    public $token;

    public function __construct($token)
    {
        $this->token = $token;
    }

    /**
     * Build the message.
     *
     * @return $this
     */
    public function build()
    {
        return $this->view('mails.confirmmail')
        ->subject('Mail confirmation');
    }
}
```

That?

**Comment by rdanusha** [comment]
It seems that no issues in your code. What is your Laravel version ?

**Comment by janva255** [comment]
@rdanusha 5.5

**Comment by janva255** [comment]
@rdanusha check out this, https://github.com/themsaid/laravel-mail-preview/issues/32

**Comment by janva255** [comment]
@rdanusha Any updates?

**Comment by janva255** [comment]
@rdanusha Wouldn't replace Swift_Mime_Message to Swift_Mime_SimpleMessage just solve the problem?

**Comment by rdanusha** [comment]
@janva255 It will solve. I'll update the repo tomorrow. Thank you for your contribution. Shall I add you as contributor?

**Comment by janva255** [comment]
@rdanusha I accepted the invite, thanks! should i merge it then? is everything ok?

**Comment by janva255** [comment]
fixed!
