### ISSUE TITLE
Symfony \ Component \ Debug \ Exception \ FatalErrorException (E_UNKNOWN) (laravel 5.6)

### ISSUE THREAD

**Issue by njoguamos** [rdanusha/LaravelElasticEmail#6]
Trying to use the package to send mail and this the error i get
Declaration of Rdanusha\LaravelElasticEmail\ElasticTransport::send(Swift_Mime_Message $message, &$failedRecipients = NULL) must be compatible with Swift_Transport::send(Swift_Mime_SimpleMessage $message, &$failedRecipients = NULL)

**Comment by janva255** [comment]
Check out this: https://github.com/rdanusha/LaravelElasticEmail/issues/3
Just get the latest version with "rdanusha/laravel-elastic-email": "dev-master" in composer.json and it'll fix your problem

**Comment by njoguamos** [comment]
It worked thanks
