### ISSUE TITLE
v1.1.2 doesn't support 5.4

### ISSUE THREAD

**Issue by Zen0x7** [rdanusha/LaravelElasticEmail#8]
Hi developers!

Today i make a `composer update` on my laravel 5.4 and this update the package to `v1.1.2`

```
Declaration of Rdanusha\LaravelElasticEmail\ElasticTransport::send() must be compatible with Swift_Transport::send(Swift_Mime_Message $message, &$failedRecipients = NULL)
```

To fix it, i use `v1.1.1`!

Please, add a message on README.md

`Use v.1.0.0 tag if you have Laravel 5.4`

Thanks dude!

**Comment by janva255** [comment]
I changed the release to 1.2 to support laravel 5.6 and added a note in the readme to notify this

**Comment by Zen0x7** [comment]
Thanks janva255!
